# Configure this Discovery Server
eureka:
  instance:
    preferIpAddress: true
  client: 
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
# HTTP (Tomcat) port
server:
  port: 1111   
